### ISSUE TITLE
Get this error when trying to do the installation

### ISSUE THREAD

**Issue by Chun-Yang** [poetic/short-stack#48]
```
Running /Users/trent/.stack.yml
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 323, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-playbook", line 263, in main
    pb.run()
  File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 310, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/Library/Python/2.7/site-packages/ansible/playbook/play.py", line 188, in __init__
    self._tasks      = self._load_tasks(self._ds.get('tasks', []), load_vars)
  File "/Library/Python/2.7/site-packages/ansible/playbook/play.py", line 661, in _load_tasks
    loaded = self._load_tasks(data, mv, role_params, default_vars, included_become_vars, list(included_additional_conditions), original_file=include_filename, role_name=new_role)
  File "/Library/Python/2.7/site-packages/ansible/playbook/play.py", line 673, in _load_tasks
    role_name=role_name
  File "/Library/Python/2.7/site-packages/ansible/playbook/task.py", line 67, in __init__
    if x in utils.plugins.module_finder:
  File "/Library/Python/2.7/site-packages/ansible/utils/plugins.py", line 205, in has_plugin
    return self.find_plugin(name) is not None
  File "/Library/Python/2.7/site-packages/ansible/utils/plugins.py", line 176, in find_plugin
    full_paths = (os.path.join(path, f) for f in os.listdir(path))
OSError: [Errno 13] Permission denied: '/Users/trent/library/Saved Application State/com.easeus.mac_drw.savedState'
```

**Comment by MatthewHager** [comment]
I think this is environment specific to you. Can't reproduce.

**Comment by levkowetz** [comment]
Run even the simplest ansible command (ansible all -m ping, for instance) in a users home directory under OS X, and you'll see this error.  The first thing I tried to do after installing ansible and setting up some hosts was the suggested 'ansible all -m ping', in my home directory, of course, and I got the exception above for every host.  Not an encouraging start.

**Comment by clarkewd** [comment]
On OS X `10.10.4` I am also experiencing this issue with ansible to `1.9.2` and `1.9.3`

This error occurs when the script can't access files in `~/library/Saved Application State` - in my case some of the files in this folder were owned by the `root` user 

You may want to try resetting the permissions on these files, perhaps with:

```
sudo chown -R "`whoami`":staff ~/library/Saved\ Application\ State
```

This should probably be addressed in `ansible/utils/plugins.py` - the script to continue even if the files can't be accessed.
